/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-11-25 08:25:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>HeartBeat</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,minimum-scale=0.1,maximum-scale=1,user-scalable=yes,viewport-fit=cover\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"title\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"description\" content=\"당신의 심장을 뛰게 하는 음악 사이트, It makes your HeartBeat\">\r\n");
      out.write("	<meta name=\"keywords\" content=\"HeartBeat,음악스트리밍,음악검색,음악듣기,팬커뮤니티,팬소통,팬소통앱,팬커뮤니티소통앱\">\r\n");
      out.write("	<meta name=\"og:title\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"og:url\" content=\"heartbeat.kr/\">\r\n");
      out.write("	<meta name=\"og:site_name\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"og:description\" content=\"당신의 심장을 뛰게 하는 음악 사이트, It makes your HeartBeat\">\r\n");
      out.write("	<meta name=\"og:image\" content=\"#none\">\r\n");
      out.write("	<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./img/favicon.ico\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/vendor/jquery-2.9.7-fullpage.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"inner main\">\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<div class=\"headerWrap\">\r\n");
      out.write("				<h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main\"></a></h1>\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"btn-full en\">Sign In</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>		\r\n");
      out.write("		<div class=\"scroll\">\r\n");
      out.write("			<span></span>\r\n");
      out.write("			<span></span>\r\n");
      out.write("			<span></span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<ul id=\"menu\" class=\"fullNav\">\r\n");
      out.write("				<li data-menuanchor=\"section-intro\" class=\"active\"><a href=\"#section-intro\"></a></li>\r\n");
      out.write("				<li data-menuanchor=\"section-makes\"><a href=\"#section-makes\"></a></li>\r\n");
      out.write("				<li data-menuanchor=\"section-hashtag\"><a href=\"#section-hashtag\"></a></li>\r\n");
      out.write("				<li data-menuanchor=\"section-community\"><a href=\"#section-community\"></a></li>\r\n");
      out.write("				<li data-menuanchor=\"section-subscribe\"><a href=\"#section-subscribe\"></a></li>\r\n");
      out.write("				<li data-menuanchor=\"section-connection\"><a href=\"#section-connection\"></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div id=\"fullpage\" class=\"fullpage\">\r\n");
      out.write("				<div class=\"section section-intro\">\r\n");
      out.write("					<div class=\"video\">\r\n");
      out.write("						<video src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/video/newjeans.mp4\" muted autoplay loop data-keepplaying playsinline></video>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"sectionWrap\">\r\n");
      out.write("						<div class=\"contents\">\r\n");
      out.write("							<div class=\"txtBx\">\r\n");
      out.write("								<div class=\"title en\">HeartBeat</div>\r\n");
      out.write("								<div class=\"subTitle\">당신의 심장을 뛰게 하는 <br class=\"mob\">팬 커뮤니티 플랫폼</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"section section-makes\">\r\n");
      out.write("					<div class=\"sectionWrap\">\r\n");
      out.write("						<div class=\"contents\">\r\n");
      out.write("							<div class=\"txtBx\">\r\n");
      out.write("								<div class=\"title en\">It makes <br class=\"web\">your <br><i class=\"c-main\">HeartBeat</i></div>\r\n");
      out.write("								<div class=\"subTitle\">음악과 소통을 동시에 하는 <br class=\"mob\">HeartBeat <br>나만의 플레이리스트를 만들고 <br>나만의 아티스트와 소통하세요.</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"imgBx\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"section section-hashtag\">\r\n");
      out.write("					<div class=\"sectionWrap\">\r\n");
      out.write("						<div class=\"contents\">\r\n");
      out.write("							<div class=\"txtBx\">\r\n");
      out.write("								<div class=\"title en\">Make your <br>Playlist <br class=\"web\"> with <br class=\"web\"><i class=\"c-main\">HASHTAG</i></div>\r\n");
      out.write("								<div class=\"subTitle\">원하는 분위기와 감성을 선택하면 <br>맞춤형 음악이 <br class=\"web\">끊임없이 <br class=\"mob\">재생되어 당신의 귀를 사로잡습니다.</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"imgBx\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"section section-community\">\r\n");
      out.write("					<div class=\"sectionWrap\">\r\n");
      out.write("						<div class=\"contents\">\r\n");
      out.write("							<div class=\"txtBx\">\r\n");
      out.write("								<div class=\"title en\">No. 1 <br>Community <br>Music Site <br><i class=\"c-main\">HeartBeat</i></div>\r\n");
      out.write("								<div class=\"subTitle\">귀로만 즐기는 것은 그만 <br>음악을 좋아하는 사람들과 소통 할 수 있는 <br>음악 커뮤니티 지금 시작하세요.</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"imgBx\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>   \r\n");
      out.write("				<div class=\"section section-subscribe\">\r\n");
      out.write("					<div class=\"sectionWrap\">\r\n");
      out.write("						<div class=\"contents\">\r\n");
      out.write("							<div class=\"txtBx\">\r\n");
      out.write("								<div class=\"title en\"><i class=\"c-main\">Subscribe</i> <br>Service</div>\r\n");
      out.write("								<div class=\"subTitle\">나의 아티스트와 소통할 수 있는 <br class=\"mob\">단 하나의 뮤직앱 <br>팬덤 커뮤니티에서 아티스트와 함께 소통하며 <br class=\"mob\">음악을 즐겨보세요.</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"imgBx\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>   \r\n");
      out.write("				<div class=\"section section-connection\">\r\n");
      out.write("					<div class=\"sectionWrap\">\r\n");
      out.write("						<div class=\"contents\">\r\n");
      out.write("							<div class=\"txtBx\">\r\n");
      out.write("								<div class=\"title en\">Start the <br><i class=\"c-main\">HeartBeat</i></div>\r\n");
      out.write("								<div class=\"subTitle\">음악만을 위해 만들어진 앱 <br>지금 하트비트를 사용해 보세요.</div>\r\n");
      out.write("								<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"btn-full en\">Subscribe to Membership</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"imgBx\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>   \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/jquery-2.9.7-fullpage.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/ScrollMagic.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/debug.addIndicators.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/TweenMax.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/animation.gsap.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function(){\r\n");
      out.write("			fullPage();\r\n");
      out.write("			scrollMagic();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function fullPage(){\r\n");
      out.write("			$('#fullpage').fullpage({\r\n");
      out.write("				anchors: ['section-intro', 'section-makes','section-hashtag','section-community','section-subscribe','section-connection'],\r\n");
      out.write("				menu: '#menu',\r\n");
      out.write("				navigation: false,\r\n");
      out.write("				scrollingSpeed: 1000,\r\n");
      out.write("				afterLoad: function(anchor, index){\r\n");
      out.write("					if(index == 1){\r\n");
      out.write("						$('#menu').fadeOut(100);\r\n");
      out.write("					}else{\r\n");
      out.write("						$('#menu').fadeIn(100);   \r\n");
      out.write("					}\r\n");
      out.write("					if(index == 6){\r\n");
      out.write("						$('.scroll').hide();\r\n");
      out.write("					}\r\n");
      out.write("					else{\r\n");
      out.write("						$('.scroll').show();\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		//https://nykim.work/30\r\n");
      out.write("		function scrollMagic() {\r\n");
      out.write("			var controller = new ScrollMagic.Controller();\r\n");
      out.write("\r\n");
      out.write("			//intro\r\n");
      out.write("			var tween_intro = TweenMax.staggerFrom('.section-intro .title', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.3\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_intro = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-intro',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_intro)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			var tween_intro = TweenMax.staggerFrom('.section-intro .subTitle', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.7\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_intro = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-intro',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_intro)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			//makes\r\n");
      out.write("			var tween_makes = TweenMax.staggerFrom('.section-makes .title', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.3\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_makes = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-makes .title',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_makes)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			var tween_makes = TweenMax.staggerFrom('.section-makes .subTitle', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.6\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_makes = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-makes',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_makes)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			var tween_makes = TweenMax.staggerFrom('.section-makes .imgBx', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.9\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_makes = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-makes',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_makes)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			//hashtag\r\n");
      out.write("			var tween_hashtag = TweenMax.staggerFrom('.section-hashtag .title', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.3\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_hashtag = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-hashtag',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_hashtag)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			\r\n");
      out.write("			var tween_hashtag = TweenMax.staggerFrom('.section-hashtag .subTitle', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.6\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_hashtag = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-hashtag',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_hashtag)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			\r\n");
      out.write("			var tween_hashtag = TweenMax.staggerFrom('.section-hashtag .imgBx', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.9\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_hashtag = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-hashtag',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_hashtag)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			//community\r\n");
      out.write("			var tween_community = TweenMax.staggerFrom('.section-community .title', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.3\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_community = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-community',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_community)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			\r\n");
      out.write("			var tween_community = TweenMax.staggerFrom('.section-community .subTitle', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.6\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_community = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-community',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_community)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			\r\n");
      out.write("			var tween_community = TweenMax.staggerFrom('.section-community .imgBx', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.9\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_community = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-community',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_community)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			//subscribe\r\n");
      out.write("			var tween_subscribe = TweenMax.staggerFrom('.section-subscribe .title', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.3\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_subscribe = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-subscribe',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_subscribe)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			\r\n");
      out.write("			var tween_subscribe = TweenMax.staggerFrom('.section-subscribe .subTitle', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.6\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_subscribe = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-subscribe',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_subscribe)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			\r\n");
      out.write("			var tween_subscribe = TweenMax.staggerFrom('.section-subscribe .imgBx', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.9\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_subscribe = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-subscribe',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_subscribe)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			//connection\r\n");
      out.write("			var tween_connection = TweenMax.staggerFrom('.section-connection .title', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.3\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_connection = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-connection',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_connection)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			var tween_connection = TweenMax.staggerFrom('.section-connection .subTitle', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.6\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_connection = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-connection',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_connection)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			var tween_connection = TweenMax.staggerFrom('.section-connection .btn-full', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 0.9\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_connection = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-connection',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_connection)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			.setTween(tween_connection)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("\r\n");
      out.write("			var tween_connection = TweenMax.staggerFrom('.section-connection .imgBx', 1.0, {\r\n");
      out.write("				ease: Sine.easeOut,\r\n");
      out.write("				opacity: 0,\r\n");
      out.write("				y: 80,\r\n");
      out.write("				delay: 1.2\r\n");
      out.write("			}, 0.2);\r\n");
      out.write("			var sub_tween_connection = new ScrollMagic.Scene({\r\n");
      out.write("				triggerElement: '.section-connection',\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("			.setTween(tween_connection)\r\n");
      out.write("			.addTo(controller)\r\n");
      out.write("			// .addIndicators({\r\n");
      out.write("			// 	name: \"connection\"\r\n");
      out.write("			// })\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
