/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-11-25 08:26:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.heartbeat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.heartbeat.music.config.SpotifyAPI;
import org.springframework.web.context.support.WebApplicationContextUtils;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpSession;

public final class chart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/kim/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/include/layout.jsp", Long.valueOf(1732522992956L));
    _jspx_dependants.put("/WEB-INF/views/include/menu.jsp", Long.valueOf(1732522992956L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1729867057530L));
    _jspx_dependants.put("jar:file:/C:/Users/kim/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("org.springframework.web.context.support.WebApplicationContextUtils");
    _jspx_imports_classes.add("kr.heartbeat.music.config.SpotifyAPI");
    _jspx_imports_classes.add("javax.servlet.ServletContext");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

    String pageName = (String) request.getAttribute("pageName");
    String pageTitle = (String) request.getAttribute("pageTitle");
	String pageRequest = request.getRequestURI();

	if (pageRequest.endsWith("index.jsp")) pageName = "HeartBeat";
	else if (pageRequest.endsWith("Web/login.jsp")) pageName = "로그인 - HeartBeat";
	else if (pageRequest.endsWith("join.jsp")) pageName = "회원가입 - HeartBeat";
	
	else if (pageRequest.endsWith("chart.jsp")){
		pageName = "차트 - HeartBeat";
		pageTitle = "차트";
	}
	else if (pageRequest.endsWith("playlist.jsp")) {
		pageName = "플레이리스트 - HeartBeat";
		pageTitle = "플레이리스트";
	}
	else if (pageRequest.endsWith("community.jsp")) {
		pageName = "커뮤니티 - HeartBeat";
		pageTitle = "커뮤니티";
	}
	else if (pageRequest.endsWith("membership.jsp")) {
		pageName = "멤버십 - HeartBeat";
		pageTitle = "멤버십";
	}
	else if (pageRequest.endsWith("mypage.jsp")) {
		pageName = "마이페이지 - HeartBeat";
		pageTitle = "마이페이지";
	}
	
	else if (pageRequest.endsWith("artist/newjeans.jsp")) {
		pageName = "뉴진스";
		pageTitle = "뉴진스";
	}
	
	else if (pageRequest.endsWith("admin/login.jsp")) {
		pageName = "관리자 로그인";
		pageTitle = "관리자 로그인";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>");
      out.print(pageName );
      out.write("</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"title\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"description\" content=\"당신의 심장을 뛰게 하는 음악 사이트, It makes your HeartBeat\">\r\n");
      out.write("	<meta name=\"keywords\" content=\"HeartBeat,음악스트리밍,음악검색,음악듣기,팬커뮤니티,팬소통,팬소통앱,팬커뮤니티소통앱\">\r\n");
      out.write("	<meta name=\"og:title\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"og:url\" content=\"heartbeat.kr/\">\r\n");
      out.write("	<meta name=\"og:site_name\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"og:description\" content=\"당신의 심장을 뛰게 하는 음악 사이트, It makes your HeartBeat\">\r\n");
      out.write("	<meta name=\"og:image\" content=\"#none\">\r\n");
      out.write("	<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/favicon.ico\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/dda279453f.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/common.js\"></script>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Spring 컨텍스트에서 SpotifyAPI Bean 가져오기
    ServletContext servletContext = application;
    SpotifyAPI spotifyAPI = (SpotifyAPI) WebApplicationContextUtils
                                .getWebApplicationContext(servletContext)
                                .getBean(SpotifyAPI.class);

    // SpotifyAPI를 사용하여 Access Token 가져오기
    String accessToken = spotifyAPI.getAccessToken();
    //Access Token 출력
   // System.out.println ("accessToken: "+accessToken );

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let isPlaying = false; // 재생 상태 관리 변수\r\n");
      out.write("    let currentYouTubeUrl = \"\";\r\n");
      out.write("\r\n");
      out.write("    async function playTrack(title, artist, e) {\r\n");
      out.write("\r\n");
      out.write("        try {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            if (!isPlaying) {\r\n");
      out.write("                const response = await fetch(`/playTrack?trackTitle=` + encodeURIComponent(title) + `&artist=` + encodeURIComponent(artist));\r\n");
      out.write("                const youTubeUrl = await response.text();\r\n");
      out.write("\r\n");
      out.write("                if (youTubeUrl === \"No URL found\") {\r\n");
      out.write("                    alert(\"Unable to find a YouTube link for this track.\");\r\n");
      out.write("                } else if (youTubeUrl === \"Error occurred\") {\r\n");
      out.write("                    alert(\"An error occurred while fetching the track.\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    // YouTube URL + 재생 옵션\r\n");
      out.write("                    const params = \"?autoplay=1&mute=0&controls=1&rel=0\";\r\n");
      out.write("                    currentYouTubeUrl = youTubeUrl + params;\r\n");
      out.write("\r\n");
      out.write("                    // iframe에 URL 설정\r\n");
      out.write("                    $(\"iframe.playerTest\").attr(\"src\", currentYouTubeUrl);\r\n");
      out.write("                    //$(\"iframe.playerTest\").css(\"display\", \"block\");\r\n");
      out.write("                    $(\".urlTest\").text(currentYouTubeUrl);\r\n");
      out.write("\r\n");
      out.write("                    isPlaying = true; // 재생 상태로 전환\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                // **일시정지: autoplay=0으로 변경하여 동영상 중지**\r\n");
      out.write("                const pausedUrl = currentYouTubeUrl.replace(\"autoplay=1\", \"autoplay=0\");\r\n");
      out.write("                $(\"iframe.playerTest\").attr(\"src\", pausedUrl);\r\n");
      out.write("                $(\".urlTest\").text(pausedUrl);\r\n");
      out.write("\r\n");
      out.write("                isPlaying = false; // 정지 상태로 전환\r\n");
      out.write("            }\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error(\"Error playing track:\", error);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.album-image {\r\n");
      out.write("		    width: 50px;  /* 이미지 너비를 50px로 설정 */\r\n");
      out.write("		    height: 50px; /* 이미지 높이를 50px로 설정 */\r\n");
      out.write("		    object-fit: cover; /* 이미지를 영역에 맞게 자르기 */\r\n");
      out.write("		}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"inner service chart\" data-name=\"chart\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String menuPageRequest = request.getRequestURI();
	
	String chart = menuPageRequest.endsWith("chart.jsp") ? "on" : "";
	String playlist = menuPageRequest.endsWith("playlist.jsp") ? "on" : "";
	String community = menuPageRequest.endsWith("community.jsp") ? "on" : "";
	String membership =	menuPageRequest.endsWith("membership.jsp") ? "on" : "";
	String mypage =	menuPageRequest.endsWith("mypage.jsp") ? "on" : "";
	
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"menu\" class=\"menu\">\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<h1 class=\"logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart\">HeartBeat</a></h1>\r\n");
      out.write("		<div class=\"userCnt\">\r\n");
      out.write("			<div class=\"user\" onclick=\"dropMenuShow();\">\r\n");
      out.write("				<div class=\"image\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/profile/user.png\" onerror=this.src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/user.png\" alt=\"닉네임\"></div>\r\n");
      out.write("				<div class=\"name\"><p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserVO.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"dropMenu\">\r\n");
      out.write("			<a href=\"/logout\" class=\"btn-under-02\">로그아웃</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menuCnt\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart\" class=\"");
      out.print(chart );
      out.write("\"><i class=\"fa-brands fa-spotify\"></i>차트</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/playlist\" class=\"");
      out.print(playlist );
      out.write("\"><i class=\"fa-solid fa-icons\"></i>플레이리스트</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/community?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserVO.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"");
      out.print(community );
      out.write(' ');
      out.print("artist".equals(request.getAttribute("artistPage")) ? "on" : "" );
      out.write("\"><i class=\"fa-solid fa-comment\"></i>커뮤니티</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/membership\" class=\"");
      out.print(membership );
      out.write("\"><i class=\"fa-solid fa-credit-card\"></i>멤버십</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/notice?num=1\" class=\"");
      out.print(mypage );
      out.write("\"><i class=\"fa-solid fa-user-pen\"></i>공지 및 문의</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\" class=\"");
      out.print(mypage );
      out.write("\"><i class=\"fa-solid fa-user-pen\"></i>마이페이지</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		<div id=\"playBar\" class=\"playBar\">플레이바</div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"cntWrap\">\r\n");
      out.write("				<h2 id=\"title\" class=\"title\">차트</h2>\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("			    \r\n");
      out.write("				<iframe  class=\"player\" \r\n");
      out.write("			    	width=\"560\" height=\"315\" src=\"\" \r\n");
      out.write("			    	frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen  style=\"display: none;\">\r\n");
      out.write("			   	</iframe>	\r\n");
      out.write("				\r\n");
      out.write("				 <iframe  class=\" playerTest\" width=\"560\" height=\"315\" \r\n");
      out.write("			        src=\"\" \r\n");
      out.write("			        frameborder=\"0\" \r\n");
      out.write("			        style=\"display: none;\"\r\n");
      out.write("			        allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" \r\n");
      out.write("			        allowfullscreen>\r\n");
      out.write("			    </iframe>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				<p class=\"urlTest\"></p>\r\n");
      out.write("				\r\n");
      out.write("				<!-- 트랙 이미지, 노래, 가수 출력 -->						\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"cntArea\">\r\n");
      out.write("					<div class=\"section-chart\">\r\n");
      out.write("						<div class=\"listBx daily\">\r\n");
      out.write("							<div class=\"titWrap\">\r\n");
      out.write("								<p class=\"subTit\">오늘 Top 10</p>\r\n");
      out.write("								<button type=\"button\" class=\"btn-under\">전체듣기</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ul class=\"itemWrap\">\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>1</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>2</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>3</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>4</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>5</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>6</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>7</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>8</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>9</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>10</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"listBx weekly\">\r\n");
      out.write("							<div class=\"titWrap\">\r\n");
      out.write("								<p class=\"subTit\">이번주 Top 10</p>\r\n");
      out.write("								<button type=\"button\" class=\"btn-under\">전체듣기</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ul class=\"itemWrap\">\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>1</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>2</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>3</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>4</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>5</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>6</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>7</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>8</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>9</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>10</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"listBx monthly\">\r\n");
      out.write("							<div class=\"titWrap\">\r\n");
      out.write("								<p class=\"subTit\">이번달 Top 10</p>\r\n");
      out.write("								<button type=\"button\" class=\"btn-under\">전체듣기</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ul class=\"itemWrap\">\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>1</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>2</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>3</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>4</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>5</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>6</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>7</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>8</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>9</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<div class=\"num\"><i>10</i></div>\r\n");
      out.write("									<div class=\"album\"><i></i></div>\r\n");
      out.write("									<div class=\"arti\">\r\n");
      out.write("										<i class=\"tit\">노래제목</i>\r\n");
      out.write("										<i class=\"name\">가수</i>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"section-station\">\r\n");
      out.write("						<p>스테이션</p>\r\n");
      out.write("						<div class=\"stationBx\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"item\" onclick=\"popStationListShow(this);\">\r\n");
      out.write("									<p class=\"tit\">드라이브 하면서 들으면 좋은 노래</p>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\" onclick=\"popStationListShow(this);\">\r\n");
      out.write("									<p class=\"tit\">운동하면서 들으면 좋은 노래</p>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\" onclick=\"popStationListShow(this);\">\r\n");
      out.write("									<p class=\"tit\">출퇴근 할 때 들으면 좋은 노래</p>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\" onclick=\"popStationListShow(this);\">\r\n");
      out.write("									<p class=\"tit\">공부 할 때 들으면 좋은 노래</p>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\" onclick=\"popStationListShow(this);\">\r\n");
      out.write("									<p class=\"tit\">노동요</p>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\" onclick=\"popStationListShow(this);\">\r\n");
      out.write("									<p class=\"tit\">잘 준비 할 때 들으면 좋은 노래</p>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"dimmed\" onclick=\"popStationListHide();\"></div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- [D] 팝업 로그아웃-->\r\n");
      out.write("	<div class=\"popup pop-alert-logout\" data-html=\"../popup/pop-alert-logout.html\"></div>\r\n");
      out.write("	<!-- [D] 팝업 스테이션 추천 리스트 -->\r\n");
      out.write("	<div class=\"popup pop-station-list\" data-html=\"../popup/pop-station-list.html\"></div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function(){\r\n");
      out.write("			colorRandom();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//팝업 스테이션\r\n");
      out.write("		function popStationListShow(e){\r\n");
      out.write("			$('.pop-station-list').show();\r\n");
      out.write("			$('.dimmed').show();\r\n");
      out.write("\r\n");
      out.write("			var stationTitle = $(e).children('.tit').text();\r\n");
      out.write("			$('#stationTitle').html(stationTitle);\r\n");
      out.write("		}\r\n");
      out.write("		function popStationListHide(){\r\n");
      out.write("			$('.pop-station-list').hide();\r\n");
      out.write("			$('.dimmed').hide();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//스테이션 배경컬러 랜덤\r\n");
      out.write("		function colorRandom(){\r\n");
      out.write("			function getRandomColor() {\r\n");
      out.write("				const letters = '0123456789ABCDEF';\r\n");
      out.write("				let color = '#';\r\n");
      out.write("				for (let i = 0; i < 6; i++) {\r\n");
      out.write("					color += letters[Math.floor(Math.random() * 16)];\r\n");
      out.write("				}\r\n");
      out.write("				return color;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function getLuminance(hex) {\r\n");
      out.write("				const r = parseInt(hex.slice(1, 3), 16) / 255;\r\n");
      out.write("				const g = parseInt(hex.slice(3, 5), 16) / 255;\r\n");
      out.write("				const b = parseInt(hex.slice(5, 7), 16) / 255;\r\n");
      out.write("\r\n");
      out.write("				const a = [r, g, b].map(function (v) {\r\n");
      out.write("					return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				const luminance = a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;\r\n");
      out.write("\r\n");
      out.write("				return luminance;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			function setRandomColors() {\r\n");
      out.write("				$('.stationBx .item').each(function() {\r\n");
      out.write("					const color = getRandomColor();\r\n");
      out.write("					$(this).css('background-color', color);\r\n");
      out.write("\r\n");
      out.write("					const luminance = getLuminance(color);\r\n");
      out.write("					const textColor = luminance > 0.5 ? '#000000' : '#FFFFFF';\r\n");
      out.write("					$(this).css('color', textColor);\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			setRandomColors();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/heartbeat/chart.jsp(119,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("trackInfo");
      // /WEB-INF/views/heartbeat/chart.jsp(119,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/heartbeat/chart.jsp(119,4) '${trackInfoList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${trackInfoList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/heartbeat/chart.jsp(119,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				    ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/heartbeat/chart.jsp(120,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index < 10}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li class=\"item\">\r\n");
          out.write("				            <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trackInfo.albumImageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"Album Image\" class=\"album-image\"/>\r\n");
          out.write("				            <i class=\"tit\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trackInfo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</i>\r\n");
          out.write("				            <i class=\"name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trackInfo.artist}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</i>\r\n");
          out.write("				          	<button class=\"play-button\"   onclick=\"playTrack('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trackInfo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trackInfo.artist}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', this)\">Play</button>\r\n");
          out.write("				          	\r\n");
          out.write("			       		</li>\r\n");
          out.write("				    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
