/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-11-25 12:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/popup/pop-add-artist.jsp", Long.valueOf(1732522992956L));
    _jspx_dependants.put("/WEB-INF/views/popup/pop-alert-purchase.jsp", Long.valueOf(1732522992956L));
    _jspx_dependants.put("jar:file:/C:/Users/kim/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/include/layout.jsp", Long.valueOf(1732522992956L));
    _jspx_dependants.put("/WEB-INF/views/include/menu.jsp", Long.valueOf(1732522992956L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1729867057530L));
    _jspx_dependants.put("jar:file:/C:/Users/kim/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

    String pageName = (String) request.getAttribute("pageName");
    String pageTitle = (String) request.getAttribute("pageTitle");
	String pageRequest = request.getRequestURI();

	if (pageRequest.endsWith("index.jsp")) pageName = "HeartBeat";
	else if (pageRequest.endsWith("Web/login.jsp")) pageName = "로그인 - HeartBeat";
	else if (pageRequest.endsWith("join.jsp")) pageName = "회원가입 - HeartBeat";
	
	else if (pageRequest.endsWith("chart.jsp")){
		pageName = "차트 - HeartBeat";
		pageTitle = "차트";
	}
	else if (pageRequest.endsWith("playlist.jsp")) {
		pageName = "플레이리스트 - HeartBeat";
		pageTitle = "플레이리스트";
	}
	else if (pageRequest.endsWith("community.jsp")) {
		pageName = "커뮤니티 - HeartBeat";
		pageTitle = "커뮤니티";
	}
	else if (pageRequest.endsWith("membership.jsp")) {
		pageName = "멤버십 - HeartBeat";
		pageTitle = "멤버십";
	}
	else if (pageRequest.endsWith("mypage.jsp")) {
		pageName = "마이페이지 - HeartBeat";
		pageTitle = "마이페이지";
	}
	
	else if (pageRequest.endsWith("artist/newjeans.jsp")) {
		pageName = "뉴진스";
		pageTitle = "뉴진스";
	}
	
	else if (pageRequest.endsWith("admin/login.jsp")) {
		pageName = "관리자 로그인";
		pageTitle = "관리자 로그인";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>");
      out.print(pageName );
      out.write("</title>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"title\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"description\" content=\"당신의 심장을 뛰게 하는 음악 사이트, It makes your HeartBeat\">\r\n");
      out.write("	<meta name=\"keywords\" content=\"HeartBeat,음악스트리밍,음악검색,음악듣기,팬커뮤니티,팬소통,팬소통앱,팬커뮤니티소통앱\">\r\n");
      out.write("	<meta name=\"og:title\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"og:url\" content=\"heartbeat.kr/\">\r\n");
      out.write("	<meta name=\"og:site_name\" content=\"HeartBeat\">\r\n");
      out.write("	<meta name=\"og:description\" content=\"당신의 심장을 뛰게 하는 음악 사이트, It makes your HeartBeat\">\r\n");
      out.write("	<meta name=\"og:image\" content=\"#none\">\r\n");
      out.write("	<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/favicon.ico\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/dda279453f.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/common.js\"></script>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function(){\r\n");
      out.write("			popAlertPurchaseShow();\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		//팝업 얼럿 멤버십구매\r\n");
      out.write("		function popAlertPurchaseShow(){\r\n");
      out.write("			if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uvo.level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" != 2) {\r\n");
      out.write("				$('.pop-alert-purchase').show();\r\n");
      out.write("				$('.dimmed').show();				\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function popAlertPurchaseHide(){\r\n");
      out.write("			$('.pop-alert-purchase').hide();\r\n");
      out.write("			$('.dimmed').hide();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//팝업 아티스트추가요청\r\n");
      out.write("		function popAddArtistShow(){\r\n");
      out.write("			$('.pop-add-artist').show();\r\n");
      out.write("			$('.dimmed').show();\r\n");
      out.write("		}\r\n");
      out.write("		function popAddArtistHide(){\r\n");
      out.write("			$('.pop-add-artist').hide();\r\n");
      out.write("			$('.dimmed').hide();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"inner service community\" data-name=\"community\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String menuPageRequest = request.getRequestURI();
	
	String chart = menuPageRequest.endsWith("chart.jsp") ? "on" : "";
	String playlist = menuPageRequest.endsWith("playlist.jsp") ? "on" : "";
	String community = menuPageRequest.endsWith("community.jsp") ? "on" : "";
	String membership =	menuPageRequest.endsWith("membership.jsp") ? "on" : "";
	String mypage =	menuPageRequest.endsWith("mypage.jsp") ? "on" : "";
	
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"menu\" class=\"menu\">\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<h1 class=\"logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart\">HeartBeat</a></h1>\r\n");
      out.write("		<div class=\"userCnt\">\r\n");
      out.write("			<div class=\"user\" onclick=\"dropMenuShow();\">\r\n");
      out.write("				<div class=\"image\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/profile/user.png\" onerror=this.src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/user.png\" alt=\"닉네임\"></div>\r\n");
      out.write("				<div class=\"name\"><p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserVO.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"dropMenu\">\r\n");
      out.write("			<a href=\"/logout\" class=\"btn-under-02\">로그아웃</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menuCnt\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chart\" class=\"");
      out.print(chart );
      out.write("\"><i class=\"fa-brands fa-spotify\"></i>차트</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/playlist\" class=\"");
      out.print(playlist );
      out.write("\"><i class=\"fa-solid fa-icons\"></i>플레이리스트</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/community?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserVO.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"");
      out.print(community );
      out.write(' ');
      out.print("artist".equals(request.getAttribute("artistPage")) ? "on" : "" );
      out.write("\"><i class=\"fa-solid fa-comment\"></i>커뮤니티</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/membership\" class=\"");
      out.print(membership );
      out.write("\"><i class=\"fa-solid fa-credit-card\"></i>멤버십</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/notice/notice?num=1\" class=\"");
      out.print(mypage );
      out.write("\"><i class=\"fa-solid fa-user-pen\"></i>공지 및 문의</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\" class=\"");
      out.print(mypage );
      out.write("\"><i class=\"fa-solid fa-user-pen\"></i>마이페이지</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"cntWrap\">\r\n");
      out.write("				<h2 id=\"title\" class=\"title\">");
      out.print(pageTitle );
      out.write("</h2>\r\n");
      out.write("				<div class=\"cntArea\">\r\n");
      out.write("					<div class=\"section-artist\">\r\n");
      out.write("						<p class=\"tit\">당신의 아티스트를 만나보세요!</p>\r\n");
      out.write("						<div class=\"artistList\">\r\n");
      out.write("							<button type=\"button\" class=\"btn-under-01\" onclick=\"popAddArtistShow();\">아티스트 추가 요청</button>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/artist/newjeans?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UserVO.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&num=1\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"item\">\r\n");
      out.write("									<a href=\"#none\">\r\n");
      out.write("										<div class=\"artist\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans.jpg\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistLogo\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/artist/newjeans-logo.png\" alt=\"newjeans\"></div>\r\n");
      out.write("										<div class=\"artistName\"><i>뉴진스</i></div>\r\n");
      out.write("									</a>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"dimmed\" onclick=\"popAlertPurchaseHide();popAddArtistHide();\"></div>\r\n");
      out.write("\r\n");
      out.write("	<!-- [D] 팝업 멤버십구매메세지 -->\r\n");
      out.write("	<div class=\"popup pop-alert-purchase\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function popAlertPurchaseHide() {\r\n");
      out.write("		window.location.href = \"/chart\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("	<div class=\"topArea\">\r\n");
      out.write("		<div class=\"title\">알림</div>\r\n");
      out.write("		<button type=\"button\" class=\"btn-i-close\" onclick=\"popAlertPurchaseHide();\"></button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"cntArea\">\r\n");
      out.write("		<div class=\"messageBx\">\r\n");
      out.write("			<p>멤버십 level 2  구매 후 이용 가능합니다.</p>\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/membership\" class=\"btn-under\">멤버십 구매하기</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("</div>\r\n");
      out.write("	<!-- [D] 팝업 아티스트추가요청 -->\r\n");
      out.write("	<div class=\"popup pop-add-artist\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("	<div class=\"topArea\">\r\n");
      out.write("		<div id=\"stationTitle\" class=\"title\">아티스트 추가 요청</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"cntArea\">\r\n");
      out.write("		<ul class=\"listBx\">\r\n");
      out.write("			<li class=\"item\">\r\n");
      out.write("				<span class=\"tit\">아티스트 이름</span>\r\n");
      out.write("				<input type=\"text\" class=\"txtBx\">\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"item\">\r\n");
      out.write("				<span class=\"tit\">요청 이유</span>\r\n");
      out.write("				<input type=\"text\" class=\"txtBx\">\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<div class=\"btnBx\">\r\n");
      out.write("			<button type=\"button\" class=\"btn-full\">요청하기</button>\r\n");
      out.write("			<button type=\"button\" class=\"btn-border\" onclick=\"popAddArtistHide();\">닫기</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
